eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostName: localhost       
server:
  port: 9000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  
  
