server:
  port: 7000
  servlet:
    context-path: /formacion
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    hostName: localhost      
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
