spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursos?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
      
server:
  port: 8081
eureka:
  instance:
    instance-id: instancia02
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
